const MAX_APP_WIDTH = 1920;
const ALERT_SHOW_TIME = 3000;
const PEER_ENV_SECRET = process.env.REACT_APP_PEER_ENV_SECRET;

const ENTITIES = {
  User: `${PEER_ENV_SECRET}_USER`,
};

export { MAX_APP_WIDTH, ALERT_SHOW_TIME, PEER_ENV_SECRET, ENTITIES };
